version: "3"

services:
  db:
    image: postgres:16
    container_name: postgres
    env_file: .docker-compose-backend-env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - backtier
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - backtier

networks:
  backtier:
    driver: bridge

volumes:
  db-data: