name: Run tests with pytest
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}
on: 
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
jobs:
  lint:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/linting.yml

  testing:
    name: Testing
    needs: [ lint ]
    if: ${{ !failure() && !cancelled() && always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    steps:
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      -
        name: Get full code
        uses: actions/checkout@v4
      -
        name: Install dependencies
        run: poetry install --no-interaction --no-root --no-directory --with dev
      -
        name: Run tests
        run: poetry run pytest
